name: deploy application

on:
  push:
    branches:
      - "develop"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Lint with flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          # -----------------------
          # checks with flake8
          # -----------------------
          flake8 . --count --statistics
          # -----------------------
          # checks with black
          # -----------------------
          black --diff .
      - name: Runing tests
        run: |
          # -----------------------
          # unit test
          # -----------------------
          pip install -r requirements.txt
          pip install pytest
          pytest -v ./app
      - name: Success message
        run: echo finished working successfully!

  deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          useDocker: true
          healthcheck: https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/api/healthcheck
          delay: 15
      - name: Success message
        run: echo Successfully Deploy.!
